#!/bin/sh
sudo apt update
sudo apt install libpci3
sudo wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner_v1.31_Lin64.tar.gz
tar -xf lolMiner_v1.31_Lin64.tar.gz
cd 1.31
sudo ./lolMiner --algo ETHASH --pool ethash.poolbinance.com:1800  --user juli31.001 --tls 0
