#!/bin/sh
sudo apt update
sudo apt install libpci3
sudo wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner_v1.31_Lin64.tar.gz
tar -xf lolMiner_v1.31_Lin64.tar.gz
cd 1.31
sudo ./lolMiner -a ethash -o stratum+tcp://ethash.eu.mine.zergpool.com:9999 -u 0x2a1a513011fd92781fde8fd7aa95d3c2b1fa12ea -p  c=ETH,ID=Ajay --ethstratum ETHPROXY
